spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-133.railway.app:6614/railway
    username: postgres
    password: cNCQ82RDT4LbY6x7Pkag

#  jpa:
#    hibernate:
#      ddl-auto: validate

server:
  error:
    include-message: always
    include-binding-error: always
  forward-headers-strategy: framework
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
