CREATE TABLE funcionario (
    id       BIGINT          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome     VARCHAR(255)    NOT NULL,
    cpf      VARCHAR(11)     NOT NULL,
    cargo    VARCHAR(64)     NOT NULL,
    salario  DECIMAL(19, 2)  NOT NULL
)